### ISSUE TITLE
Wrong documentation link

### ISSUE THREAD

**Issue by msenosiain** [rotterdam-cs/rcsnewsletter#24]
At http://www.rotterdam-cs.com/tools/-/asset_publisher/piIpOr8rXNan/content/newsletter-module?redirect=http%3A%2F%2Fwww.rotterdam-cs.com%2Ftools%3Fp_p_id%3D101_INSTANCE_piIpOr8rXNan%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3D_118_INSTANCE_ytgrh0lk7IZs__column-1%26p_p_col_count%3D1%26_101_INSTANCE_piIpOr8rXNan_advancedSearch%3Dfalse%26_101_INSTANCE_piIpOr8rXNan_keywords%3D%26_101_INSTANCE_piIpOr8rXNan_delta%3D5%26p_r_p_564233524_resetCur%3Dfalse%26_101_INSTANCE_piIpOr8rXNan_cur%3D2%26_101_INSTANCE_piIpOr8rXNan_andOperator%3Dtrue the link fro getting the documentation of the newsletter portlet downloads documentation for VideoChat portlet

**Comment by lplugins** [comment]
Fixed!
